### ISSUE TITLE
What about Gate Facade and policy ?

### ISSUE THREAD

**Issue by imanghafoori1** [boomcms/boom-core#134]
Don't you intend to use Gate Facade and policy objects introduced in Laraval 5.1.16 and above ?!

**Comment by imanghafoori1** [comment]
I am currently studying you project in order to learn tips and tricks and etc from your code...
I can help you in refactoring... If you like to.

**Comment by robbytaylor** [comment]
Hi Iman,

Thanks for your interest in BoomCMS.

We certainly do intend to make use of the gate facade and policy objects. To give you a bit of background BoomCMS was originally developed using the Kohana framework. We migrated to Laravel when development of Kohana stagnated. Boom therefore doesn't yet completely take advantage of all the features which Laravel provides.

We currently aim for a monthly release cycle with a new version released on or around the third Monday of the month. Each release includes some refactoring to make better use of Laravel's features. The authentication component of Boom is now the area which is least integrated with Laravel. I'm therefore intending to refactor that and make use of the gate facade and policy objects in time for either the January (18th) or February (15th) releases.

We'd happily accept pull requests. There's a few other (smaller) areas of refactoring which can be done as well to integrate Laravel better (e.g. Eloquent attribute casting). I'll create a separate issue for those.

Rob

**Comment by imanghafoori1** [comment]
You mean you push your changes to github only every month ?

 I do wanted to mention you about a package called pingpong/modules.
The asgardCMS (which is also base on laravel) uses it to modularize their CMS to smaller sub applications.
Do check it out if have to already.
I want to use it in my own project at work.

**Comment by imanghafoori1** [comment]
I take my weekends to study you code and help you if I am able to.

**Comment by imanghafoori1** [comment]
Another note I did forget to mention is using Jade templating language with laravel-elixir.
We are using it at work for a while and our front-end developers are totally happy with it.
Take a look at :
jade-lang.org
html2jade.org
https://www.npmjs.com/package/laravel-elixir-jade
https://gist.github.com/imanghafoori1/7eeb0ffe9d205acc9210

**Comment by robbytaylor** [comment]
Hi Iman,

We push changes to the master branch on GitHub as and when we make them. By monthly release cycle I mean that we 'tag' a new release once a month. The master branch is our development branch so should be assumed to be ready for use on a production site. When we tag the release it's ready for us on production.

Thanks for the tip about those other packages, I'll check them out.

Rob
